export const ErrorCode = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_NOT_CONFIRMED: "AUTH_EMAIL_NOT_CONFIRMED",
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  WORKSPACE_FORBIDDEN: "WORKSPACE_FORBIDDEN",
  STORY_NOT_FOUND: "STORY_NOT_FOUND",
  NODE_NOT_FOUND: "NODE_NOT_FOUND",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  EDGE_NOT_FOUND: "EDGE_NOT_FOUND",
  INVALID_NODE_TYPE: "INVALID_NODE_TYPE",
  INVALID_START_EDGE: "INVALID_START_EDGE",
  INVALID_GOAL_EDGE: "INVALID_GOAL_EDGE",
  EDGE_ALREADY_EXISTS: "EDGE_ALREADY_EXISTS",
  GRAPH_CYCLE_DETECTED: "GRAPH_CYCLE_DETECTED",
  TASK_BLOCKED: "TASK_BLOCKED",
  INVALID_TASK_STATUS: "INVALID_TASK_STATUS",
  PUSH_ENDPOINT_TAKEN: "PUSH_ENDPOINT_TAKEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
